services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak-auth:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak-auth
    command: start-dev --import-realm --health-enabled=true
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./backend/realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8181:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-server:
    build: ./backend/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_started

  config-server:
    build: ./backend/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./backend/config-repo:/app/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/app/config-repo
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8880:8080"
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak-auth:8080/realms/ecommerce-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak-auth:8080/realms/ecommerce-realm/protocol/openid-connect/certs
    depends_on:
      discovery-server:
        condition: service_started
      keycloak-auth:
        condition: service_healthy

  product-service:
    build: ./backend/product-service
    container_name: product-service
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      discovery-server:
        condition: service_started
      postgres-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  forum-service:
    build: ./backend/services/forum-service
    container_name: forum-service
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_started

  order-service:
    build: ./backend/micro_s_ordre
    container_name: order-service
    restart: on-failure
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/order_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      discovery-server:
        condition: service_started
      mysql-db:
        condition: service_healthy
      config-server:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  event-service:
    build: ./backend/services/event_service
    container_name: event-service
    restart: on-failure
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/event_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      discovery-server:
        condition: service_started
      mysql-db:
        condition: service_healthy
      config-server:
        condition: service_started
