services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-auth:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak-auth
    command: start-dev --import-realm --health-enabled=true
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./backend/realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8181:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-server:
    build: ./backend/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_started

  config-server:
    build: ./backend/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./backend/config-repo:/app/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/app/config-repo
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_started
      keycloak-auth:
        condition: service_healthy

  product-service:
    build: ./backend/product-service
    container_name: product-service
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_started
      postgres-db:
        condition: service_healthy
