server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/forum-service/**
          filters:
            - RewritePath=/forum-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/**
          filters:
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event-service/**
          filters:
            - RewritePath=/event-service/(?<segment>.*), /$\{segment}
        # Swagger routes for each service
        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
  api-docs:
    path: /v3/api-docs